# run with docker-compose up --abort-on-container-exit
version: '2'

services:

  haxe:
    build:
      context: "."
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      # - ./build:/app/build
    # image: "haxe:3.4.2"
    # command: ["node", "server/cloud-compute-cannon-server.js"]
    command: ["/bin/bash", "./test/runtests.sh"]
    links:
      - redis

  redis:
    # image: "dionjwa/cloud-compute-cannon-redis:0.2.2"
    image: "redis:4-alpine"
    ports:
      - "6379:6379"

  redis-commander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis
    ports:
      - "8081:8081"